### ISSUE TITLE
Diagnostics don't not respect Rubocop excludes

### ISSUE THREAD

**Issue by cseelus** [neoclide/coc-solargraph#36]
For example in a Rails project, `schema.rb` gets linted, despite being excluded.

Here is a minimal [.rubocop.yml config for Rails projects from the Rubocop docs](https://docs.rubocop.org/rubocop/configuration.html), where the excludes get ignored:

```yml
AllCops:
  Exclude:
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'bin/{rails,rake}'
```

When setting other Linting options like maximum line length, they work though.
