### ISSUE TITLE
Not respecting my rubocopy.yml excludes

### ISSUE THREAD

**Issue by npearson72** [neoclide/coc-solargraph#43]
I have the following in my rubocop.yml, but I'm still getting linting on my specs:

```
AllCops:
  TargetRubyVersion: 2.6
  TargetRailsVersion: 5.0
  Exclude:
    - "bin/**/*"
    - "node_modules/**/*"
    - "vendor/**/*"
    - "spec/**/*.rb"
```

Any ideas?
